name: lint

on:
  push:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'
  pull_request:
    branches: [main]
    paths-ignore:
      - 'README.md'
      - 'LICENSE'
      - 'docs/**'
      - '.gitignore'
      - '.github/ISSUE_TEMPLATE/**'

jobs:
  shell-lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # ratchet:actions/checkout@v4

      - name: Install ShellCheck and shfmt
        run: |
          sudo apt-get update
          sudo apt-get install -y shellcheck
          curl -sSLo /usr/local/bin/shfmt https://github.com/mvdan/sh/releases/download/v3.12.0/shfmt_v3.12.0_linux_amd64
          sudo chmod +x /usr/local/bin/shfmt

      - name: Run ShellCheck
        run: |
          shellcheck -S warning scripts/*.sh || {
            echo "ShellCheck issues found"; exit 1; }

      - name: Check formatting with shfmt
        run: |
          shfmt -d -i 2 -ci -s scripts || {
            echo "shfmt found formatting differences (run: shfmt -w -i 2 -ci -s scripts)"; exit 1; }
